#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
org.gradle.configuration-cache=false
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
